# Generated by Django 5.2.4 on 2025-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
