# Generated by Django 5.2.4 on 2025-07-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='mens',
        ),
    ]
